server.port=8080
spring.application.name=wordguess-backend

# MongoDB configuration (Default: local instance wordguess_db)
spring.data.mongodb.uri=mongodb+srv://kusumasrivalli4_db_user:oueiZmMa3uzM6Hg6@cluster0.nvyhzav.mongodb.net/?appName=Cluster0
spring.data.mongodb.auto-index-creation=true

# Logging
logging.level.com.wordguess=INFO
logging.level.org.springframework.data.mongodb=INFO
