server.port=8080
spring.application.name=wordguess-backend

# MongoDB configuration (Default: local instance wordguess_db)
spring.data.mongodb.uri=your_mongo_db_uri
spring.data.mongodb.auto-index-creation=true

# Logging
logging.level.com.wordguess=INFO
logging.level.org.springframework.data.mongodb=INFO
